VCS abstraction layer now works for git and hg
Not fully tested for hg, but seems to be working.  This enables
generation of both hg and git versions of the zoneinfo trees.

diff --git a/work/cpsettz b/work/cpsettz
--- a/work/cpsettz
+++ b/work/cpsettz
@@ -2,4 +2,8 @@
 
 VCS=${1-git}
 
+if [[ -d $VCS.tz ]]; then
+  echo "ERROR: $VCS.tz already exists."
+  exit 1
+fi
 cp -a ../work-usenet/$VCS.settz $VCS.tz
